"""Add transaction and webhook log tables

Revision ID: 0001
Revises: 
Create Date: 2025-10-28 11:20:58.307112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('source_account', sa.String(length=255), nullable=False),
    sa.Column('destination_account', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'PROCESSED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id', name='uq_transaction_id'),
    schema='transaction_webhook'
    )
    op.create_index(op.f('ix_transaction_webhook_transactions_id'), 'transactions', ['id'], unique=False, schema='transaction_webhook')
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='transaction_webhook'
    )
    op.create_index(op.f('ix_transaction_webhook_webhook_logs_id'), 'webhook_logs', ['id'], unique=False, schema='transaction_webhook')
    op.create_index(op.f('ix_transaction_webhook_webhook_logs_transaction_id'), 'webhook_logs', ['transaction_id'], unique=False, schema='transaction_webhook')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_webhook_webhook_logs_transaction_id'), table_name='webhook_logs', schema='transaction_webhook')
    op.drop_index(op.f('ix_transaction_webhook_webhook_logs_id'), table_name='webhook_logs', schema='transaction_webhook')
    op.drop_table('webhook_logs', schema='transaction_webhook')
    op.drop_index(op.f('ix_transaction_webhook_transactions_id'), table_name='transactions', schema='transaction_webhook')
    op.drop_table('transactions', schema='transaction_webhook')
    # ### end Alembic commands ###
